### ISSUE TITLE
AMD that returns function breaks conversions

### ISSUE THREAD

**Issue by dcalhoun** [buxlabs/amd-to-es6#17]
It would appear that an AMD block that returns a `function` breaks the conversion. The following...

```javascript
define(['marionette'], (Marionette) =>
  () => {}
)
```

Throws...
```javascript
/Users/user/Sites/other/es6-migrate/node_modules/@buxlabs/amd-to-es6/src/lib/generateCode.js:98
    var nodes = code.map(function (node) {
                     ^

TypeError: code.map is not a function
    at module.exports (/Users/user/Sites/other/es6-migrate/node_modules/@buxlabs/amd-to-es6/src/lib/generateCode.js:98:22)
    at Module.convert (/Users/user/Sites/other/es6-migrate/node_modules/@buxlabs/amd-to-es6/src/class/Module.js:19:20)
    at module.exports (/Users/user/Sites/other/es6-migrate/node_modules/@buxlabs/amd-to-es6/src/converter.js:14:12)
    at convertFile (/Users/user/Sites/other/es6-migrate/node_modules/@buxlabs/amd-to-es6/bin/cli.js:37:20)
    at Object.<anonymous> (/Users/user/Sites/other/es6-migrate/node_modules/@buxlabs/amd-to-es6/bin/cli.js:65:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by emilos** [comment]
@dcalhoun thanks again! Fixed in https://github.com/buxlabs/amd-to-es6/commit/bc8d2267e44b73166bd759c8112d646cdababbbc and published as `0.8.2`.
